# Generated by Django 4.0.4 on 2022-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=100)),
                ("nom", models.CharField(blank=True, max_length=200, null=True)),
                ("prenom", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VM",
            fields=[
                (
                    "hostname",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("cpu", models.PositiveIntegerField(default=0)),
                ("ram", models.PositiveIntegerField(default=0)),
                ("os", models.CharField(max_length=200)),
            ],
        ),
    ]
