# Generated by Django 4.0.4 on 2022-05-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_vm_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapUserVM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="vm",
            name="users",
            field=models.ManyToManyField(
                related_name="vms", through="myapp.MapUserVM", to="myapp.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("nom", "prenom")},
        ),
        migrations.AddField(
            model_name="mapuservm",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.person"
            ),
        ),
        migrations.AddField(
            model_name="mapuservm",
            name="vm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.vm"
            ),
        ),
    ]
